global:
  mailboxes:
    mail.example.com:
      host: imap.example.com
      login: mail@example.com
      password: foobar
      ssl: true
      skip: "foo,bar.baz"
  notifications:
    tokens: my_64_letters_token
